force-app/main/default/objects/Discount_Settings__mdt/fields/Discount_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Discount_Strategy__c</fullName>
    <label>Discount Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Highest Discount</fullName>
                <default>true</default>
                <label>Highest Discount</label>
            </value>
            <value>
                <fullName>Lowest Discount</fullName>
            </value>
            <value>
                <fullName>Combine Discounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount_Settings__mdt/fields/Minimum_Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Discount_Percentage__c</fullName>
    <label>Minimum Discount Percentage</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DiscountSettingsUtils.cls
public class DiscountSettingsUtils {

    public String FULL_NAME      { get { return 'Discount_Settings__mdt.Default'; } }
    public String LABEL          { get { return 'Default'; } }
    public String DEVELOPER_NAME { get { return 'Default'; } }

    public final FieldConst FIELD = new FieldConst();

    public class FieldConst {
        public String STRATEGY { get { return 'Discount_Strategy__c'; } }
        public String MIN_PCT  { get { return 'Minimum_Discount_Percentage__c'; } }
    }
}